name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install --global yarn
        yarn install --dev
        yarn build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        path: dist/

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.3
